Add envelope fix quirk and value clamping functions
JacKeTUs/moza-ff pull request #5
Opened 2024-07-02 10:08 UTC by Lawstorant

This updates the universal quirks branch.

I still think we should try to keep 100% compatibility with pidff so it will be easier to upstream it when we fell like we're ready. I reverted some name changes but of course you can update them after merging if you don't feel like you like them.

I just see no reason to potentially duplicate pidff code as we could just improve it for generic pidff devices.

2024-07-12 11:11 UTC, JacKeTUs requested changes
Just hide magic number into preprocessor, everything else LGTM

2024-07-12 11:11 UTC, JacKeTUs commented on hid-pidff.c
> +		direction = 0x4000;
Can you please move that magic number to `#define`? And may be explain in comments why it's exactly that number

2024-07-12 13:48 UTC, Lawstorant commented on hid-pidff.c
> +		direction = 0x4000;
Done

2024-07-13 11:15 UTC, JacKeTUs requested changes

2024-07-13 14:02 UTC, Lawstorant commented on dkms.conf
> +BUILT_MODULE_NAME[0]="hid-univesal-pidff"
Oh, well. I was just testing this out and fixed it as well.

2024-07-13 14:02 UTC, Lawstorant commented on dkms.conf
> +BUILT_MODULE_NAME[0]="hid-univesal-pidff"
Now it works. Confirmed by installing the driver from aur instead of just manually insmoding from repository

2024-07-13 21:03 UTC, JacKeTUs approved these changes

2024-07-14 20:08 UTC, merged